name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  { pattern = "inconigto-mode.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto-mode.web.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto-mode.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto-mode.web.id", custom_domain = true },

  { pattern = "inconigto.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.inconigto.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto.biz.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto.biz.id", custom_domain = true },

  { pattern = "inconigto.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.inconigto.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto.web.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto.web.id", custom_domain = true },
]


[[kv_namespaces]]
binding = "SIREN"
id = "f8c606840cbf0c35d63c4cb5512292c4"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "cc39b378-0ed3-44b7-be2a-fe119fa61b00"
MAIN_PAGE_URL = "https://raw.github.com/KAISARVPN/vipsteam/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.github.com/KAISARVPN/vipsteam/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.github.com/KAISARVPN/vipsteam/refs/heads/master/web/link.html"
